reverted paymentype enum change to string as  java.lang.NoSuchMethodError: No virtual method
as per discuss with Ola reverted the change to finsih the UI
java.lang.NoSuchMethodError: No virtual method